language: cpp

os: 
  - linux

dist: trusty
sudo: required 

env:
  - PYTHON=2.7 NUMPY=numpy ENERGYPLUS_VERSION=8.5.0 ENERGYPLUS_SHA=c87e61b44b ENERGYPLUS_INSTALL_VERSION=8-5-0
  - PYTHON=2.7 NUMPY=tinynumpy ENERGYPLUS_VERSION=8.5.0 ENERGYPLUS_SHA=c87e61b44b ENERGYPLUS_INSTALL_VERSION=8-5-0
  - PYTHON=3.5 NUMPY=numpy ENERGYPLUS_VERSION=8.5.0 ENERGYPLUS_SHA=c87e61b44b ENERGYPLUS_INSTALL_VERSION=8-5-0
  - PYTHON=3.5 NUMPY=tinynumpy ENERGYPLUS_VERSION=8.5.0 ENERGYPLUS_SHA=c87e61b44b ENERGYPLUS_INSTALL_VERSION=8-5-0

before_install:
  # activate virtual env
  - if [[ $PYTHON == 2* ]]; then virtualenv venv -p python; fi
  - if [[ $PYTHON == 3* ]]; then virtualenv venv -p python3; fi
  - source venv/bin/activate

  # coverage and testing requirements
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install pytest-cov
  - pip install codecov
  

install:
  - python setup.py install 
  # install numpy and remove tinynumpy if testing with numpy
  - if [[ $NUMPY == numpy ]]; then pip install numpy; pip uninstall tinynumpy -y; fi

script:
  # run all tests in tests and check coverage of the geomeppy dir
  - py.test -v --cov-config .coveragerc --cov=geomeppy tests

after_success:
  # coverage reporting on CodeCov 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] &&
       [[ $PYTHON == 3* ]] &&
       [[ $NUMPY == numpy ]]; then codecov; fi
    