language: cpp

os:
  - linux

sudo: required
dist: trusty

env:
  - PYTHON=2.7
  - PYTHON=3.5
  - PYTHON=3.6

before_install:
  # miniconda
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

  # create miniconda env
  - conda create --yes -n geomeppy python=$PYTHON
  - source activate geomeppy

install:
  - pip install -e .[testing]

before_script:
  - flake8 --count geomeppy
  - if [[ $PYTHON == 3.6 ]]; then mypy --ignore-missing-imports geomeppy || :; fi  # force a zero return code

script:
  # run all tests in tests and check coverage of the geomeppy dir
  - py.test -v --cov-config .coveragerc --cov=geomeppy tests

after_success:
  # coverage reporting on CodeCov
  - if [[ $PYTHON == 3.6 ]]; then codecov; fi

deploy:
  provider: pypi
  user: JamieBull
  password:
    secure: krobKK/9orQpsrZ5hD4XfT7ZvWFMssMQmVd4CkK3p1SzkrY96tfjVJU0DtYRvF4cIljExYNhJrwOrtyaCYy/IKgh/wA8cMKBImkOB94RLA7hx8QOEpFkxOa0XyMBZaxWtw1mB/PJ9+t4kirzlC1nU0HVQUSBmjyAEhYr5w7+n39bP61UHEuEiaw86Zhnpcwf6yj1EWc04raRfwf3f5TPmgpQlppohCvfc7jxU5/NZFCUPRpYxQ+OxQRVzKl0SgY6ifWOAXmuTJv5/mHr3TaV1cDZqNrpmLTIEHb0B/n5AF2rDB6/Ea+Ahlw1nAOuRUHnvR4lqMA/uYAc6GcwNxwAdwD8juJuZ5Cl9JEIzD0jGIdmOC/IxPUY2CnRVOtfTSsH4a0Wfh86rx9VNyJhBcZXYRaDw0CvsbiEmZhEgmQDEaEE9w95zQFMSDHbGTlkFMto6ajD6petzptm7cgqxGGAoJjKlUWvUjlXQtLSdAL1wn7CRgBsXWMIWAvW8HFyfO6/yaH7sr6U70dlA9UV4d9nDOyc2eNNujhfpRWZWAZv4YM47yu8lEnPJWOT7M2S4w40OyJNKFhMo74duLhAd9t+zg4MAGmIATGKJi3XMPUdJwSl182jGEx/Cye07vmKdfKWnHFtyJbRcyOuKTP2aiaYGUDInCQLr/wbzZlQ1A4Jovs=
