language: cpp

os: 
  - linux

sudo: required
dist: trusty

env:
  - PYTHON=2.7
  - PYTHON=3.5
  - PYTHON=3.6

before_install:
  # miniconda
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  
  # create miniconda env
  - conda create --yes -n geomeppy python=$PYTHON
  - source activate geomeppy
  - conda install --yes numpy matplotlib pip
  - conda install --yes -c conda-forge shapely

install:
  - pip install -e .[testing]

script:
  # run all tests in tests and check coverage of the geomeppy dir
  - py.test -v --cov-config .coveragerc --cov=geomeppy tests

after_success:
  # coverage reporting on CodeCov 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] &&
       [[ $PYTHON == 2* ]]; then codecov; fi
    
